### PR TITLE
Plot Tabs Refactor

### PR DESCRIPTION
**Pull request by paulnordlund**
Jira tasks include:

IPAD-353: Single/Multi-Feature 'tab' in Plots Container
- separates tabs into separate components with their own state

IPAD-369: SVG Plot Issues/Requests
- ensures they update accurately and when they need to
- ignores unknown plot types (JB request)

IPAD-376: Scatter plot - shift to box select multiple features
- adds shift box select functionality

### CODE REVIEW

**Review by ternst23 — CHANGES_REQUESTED** [review]
Please investigate export from Mulit-Feature plots

**Review by JoeDalen81 — APPROVED** [review]
Looks good however, I think this is a mac issue, with the "shift to box select" functionality I noticed the table doesn't update like it does when shift clicking individual features from the scatterplot.  In order to "shift click" features individually I have to use the command button instead of shift and it works fine.  You might have to do the same thing for "shift to box select", I believe for the command key on a mac its called "d3.event.metaKey".  Still approving since I think this is mac specific.

**Comment by paulnordlund** [comment]
> Looks good however, I think this is a mac issue, with the "shift to box select" functionality I noticed the table doesn't update like it does when shift clicking individual features from the scatterplot. In order to "shift click" features individually I have to use the command button instead of shift and it works fine. You might have to do the same thing for "shift to box select", I believe for the command key on a mac its called "d3.event.metaKey". Still approving since I think this is mac specific.

Thanks for reviewing Joe. The "metaKey" is Command on Mac, and Windows key on Windows. You added code to allow it when highlighting a single feature in the scatter plot (Control-clicked: Windows)/Command-clicked: Mac). The table pages to that single feature when it is outlined or highlighted, but when selecting multiple features in the scatter plot (Windows and Mac: Shift-Click), the table purposely doesn't page since there are multiple features and it seems reasonable not to choose one. I previously discussed this with Brett/Terry and we agreed on that, for now.

This pull request was able to override D3 brush default events (only brush if no buttons are being held, or if the "metaKey" is being held) by adding - .filter(() => true, in conjunction with turning off key modifiers - keyModifiers(false). Otherwise holding Shift wouldn't initiate a brush. Note: Holding shift AFTER starting the brush would work and still allow key modifiers (holding down the ALT (⌥) key while moving the brush causes it to reposition around its center, while holding down SPACE locks the current brush size, allowing only translation.) However, I discussed it with both Brett and Terry and they believed holding Shift before starting to brush was more intuitive and worth the trade-off.

**Comment by paulnordlund** [comment]
Additional work completed on December 17th to meet PO requests:
- added padding to results table bottom so users can more easily click on table page numbers
- enlarged default circle radius, so users can more easily control-click
- added whitespace between 'options', 'usage guide', etc and plot to facilitate box selection and point selection
- remove table paging/scrolling for multi-feature selection; only page/scroll on single-feature selection
- bug fix: options dropdown change caused bug when it ran into features without data for that specific column; refactored to use feature id, rather than state variable "identifier" (removed completely)
@bengalengel, please review when convenient and if all good, we'll merge and release

**Pull request merged**
